### ISSUE TITLE
Add Coding Style Guide

### ISSUE THREAD

**Issue by michaelbiberich** [Thejuse/CMS-Installer#6]
Strong candidates for PHP based projects would be [PSR-1](http://www.php-fig.org/psr/psr-1/) and [PSR-2](http://www.php-fig.org/psr/psr-2/).

Although [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) looks promising its still in _Draft_ (should be reevaluated once _Accepted_).

The projects Coding Style Guide should be referenced in other meta files too (eg. README, Contributing Guidelines, etc.).

**Comment by Thejuse** [comment]
Done In Recode
